import type { BookInput } from '@/db/database';

const cover = (title: string, bg: string) =>
  `https://placehold.co/300x430/${bg}/FFFFFF/png?text=${encodeURIComponent(title)}`;

const base: Omit<BookInput, 'title'> = {
  author: '',
  publisher: null,
  genre: null,
  cover_local_path: null,
  start_date: null,
  finish_date: null,
  is_owned: 1,
  is_stopped: 0,
  stopped_date: null,
  from_wishlist: 0,
  wishlist_added_date: null,
  rating: null,
  short_review: null,
  memo: null,
  read_count: 1,
};

export const SAMPLE_BOOKS: BookInput[] = [
  {
    ...base,
    title: '채식주의자',
    author: '한강',
    publisher: '창비',
    genre: '소설',
    cover_local_path: cover('채식주의자', '6B8E7F'),
    start_date: '2026-04-02',
    finish_date: '2026-04-06',
    rating: 5,
    short_review: '조용한 파열음, 오래 남는 문장들',
  },
  {
    ...base,
    title: '아주 작은 습관의 힘',
    author: '제임스 클리어',
    publisher: '비즈니스북스',
    genre: '자기계발',
    cover_local_path: cover('Atomic+Habits', 'E07A5F'),
    start_date: '2026-04-05',
    finish_date: '2026-04-10',
    rating: 4,
    short_review: '1% 의 복리를 믿게 되는 책',
  },
  {
    ...base,
    title: '무례한 사람에게 웃으며 대처하는 법',
    author: '정문정',
    publisher: '가나출판사',
    genre: '에세이',
    cover_local_path: cover('무례한+사람에게', '81B29A'),
    start_date: '2026-04-08',
    finish_date: '2026-04-12',
    rating: 4,
  },
  {
    ...base,
    title: '파친코',
    author: '이민진',
    publisher: '인플루엔셜',
    genre: '소설',
    cover_local_path: cover('파친코', '3D405B'),
    start_date: '2026-04-11',
    finish_date: null,
    rating: null,
  },
  {
    ...base,
    title: '소년이 온다',
    author: '한강',
    publisher: '창비',
    genre: '소설',
    cover_local_path: cover('소년이+온다', '5B6C8C'),
    start_date: '2026-03-02',
    finish_date: '2026-03-08',
    rating: 5,
    short_review: '시대를 관통하는 통증의 서사',
  },
  {
    ...base,
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    publisher: '흔',
    genre: '에세이',
    cover_local_path: cover('떡볶이', 'F2CC8F'),
    start_date: '2026-03-05',
    finish_date: '2026-03-10',
    rating: 3,
  },
  {
    ...base,
    title: '미움받을 용기',
    author: '기시미 이치로',
    publisher: '인플루엔셜',
    genre: '자기계발',
    cover_local_path: cover('미움받을+용기', 'C1574C'),
    start_date: '2026-03-09',
    finish_date: '2026-03-15',
    rating: 5,
    short_review: '아들러 심리학으로 삶을 정돈하기',
  },
  {
    ...base,
    title: '나의 라임 오렌지나무',
    author: 'J.M.바스콘셀로스',
    publisher: '동녘',
    genre: '소설',
    cover_local_path: cover('라임+오렌지', 'A8C686'),
    start_date: '2026-03-16',
    finish_date: '2026-03-22',
    rating: 4,
  },
  {
    ...base,
    title: '마흔에 읽는 쇼펜하우어',
    author: '강용수',
    publisher: '유노북스',
    genre: '에세이',
    cover_local_path: cover('쇼펜하우어', '6D597A'),
    start_date: '2026-03-20',
    finish_date: '2026-03-28',
    rating: 4,
  },
  {
    ...base,
    title: '세이노의 가르침',
    author: '세이노',
    publisher: '데이원',
    genre: '자기계발',
    cover_local_path: cover('세이노의+가르침', '2B2D42'),
    start_date: '2026-04-01',
    finish_date: null,
    rating: null,
  },
];
