import type { WishlistInput } from '@/db/database';

export const SAMPLE_WISHLIST: WishlistInput[] = [
  {
    title: '클라라와 태양',
    author: '가즈오 이시구로',
    publisher: '민음사',
    genre: '소설',
    memo: '이시구로 신작, AI 친구가 바라본 인간의 사랑',
    cover_local_path: null,
    created_at: '2025-11-03 10:24:00',
  },
  {
    title: '도둑맞은 집중력',
    author: '요한 하리',
    publisher: '어크로스',
    genre: '자기계발',
    memo: '스마트폰 시대 집중력 회복',
    cover_local_path: null,
    created_at: '2025-12-17 21:05:00',
  },
  {
    title: '시간은 흐르지 않는다',
    author: '카를로 로벨리',
    publisher: '쌤앤파커스',
    genre: '과학',
    memo: '물리학자가 쓴 시간에 대한 통찰',
    cover_local_path: null,
    created_at: '2026-01-24 08:41:00',
  },
  {
    title: '불안',
    author: '알랭 드 보통',
    publisher: '은행나무',
    genre: '인문',
    memo: '현대인의 불안을 철학으로 풀어내기',
    cover_local_path: null,
    created_at: '2026-02-18 19:12:00',
  },
  {
    title: '작별하지 않는다',
    author: '한강',
    publisher: '문학동네',
    genre: '소설',
    memo: '노벨문학상 수상작가 한강의 신작',
    cover_local_path: null,
    created_at: '2026-03-11 14:50:00',
  },
  {
    title: '넥서스',
    author: '유발 하라리',
    publisher: '김영사',
    genre: '인문',
    memo: 'AI 시대 정보망과 권력에 대한 이야기',
    cover_local_path: null,
    created_at: '2026-04-07 22:30:00',
  },
  {
    title: '아주 사적인 글쓰기',
    author: '은유',
    publisher: '유유히',
    genre: '에세이',
    memo: '나만의 문장을 찾아가는 글쓰기 안내서',
    cover_local_path: null,
    created_at: '2026-03-02 09:15:00',
  },
  {
    title: '공정하다는 착각',
    author: '마이클 샌델',
    publisher: '와이즈베리',
    genre: '인문',
    memo: '능력주의의 덫을 짚어보는 책',
    cover_local_path: null,
    created_at: '2026-03-27 18:02:00',
  },
  {
    title: '물고기는 존재하지 않는다',
    author: '룰루 밀러',
    publisher: '곰출판',
    genre: '에세이',
    memo: '분류의 신화를 깨트리는 이야기',
    cover_local_path: null,
    created_at: '2026-02-05 12:44:00',
  },
  {
    title: '달러구트 꿈 백화점',
    author: '이미예',
    publisher: '팩토리나인',
    genre: '소설',
    memo: '잠든 사이 꾸는 꿈을 파는 가게',
    cover_local_path: null,
    created_at: '2026-01-09 20:10:00',
  },
];
